/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package db;

import java.io.FileWriter;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author osman
 */
public class FrmAddUser extends javax.swing.JPanel {

    /**
     * Creates new form FrmAddUser
     */
    FrmUser parent;
    String currentName="";
    boolean isEdited=false;
    DatabaseType db=new DatabaseType();

    ButtonGroup single=new ButtonGroup();
    
    
    public FrmAddUser(FrmUser p) {
        initComponents();
        parent=p;
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JPasswordField();
        txtPassword1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmdSave = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();
        cmdReset = new javax.swing.JButton();
        optAdmin = new javax.swing.JCheckBox();
        optAudit = new javax.swing.JCheckBox();
        optBooking = new javax.swing.JCheckBox();
        optStatus = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(13, 71, 93));
        setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reports");
        add(jLabel2);
        jLabel2.setBounds(100, 250, 90, 30);

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        add(txtUserName);
        txtUserName.setBounds(220, 90, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("User Info");
        add(jLabel6);
        jLabel6.setBounds(190, 10, 160, 50);
        add(txtPassword2);
        txtPassword2.setBounds(220, 180, 200, 30);
        add(txtPassword1);
        txtPassword1.setBounds(220, 130, 200, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        add(jLabel3);
        jLabel3.setBounds(100, 90, 90, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        add(jLabel4);
        jLabel4.setBounds(100, 130, 90, 30);

        cmdSave.setText("Save");
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });
        add(cmdSave);
        cmdSave.setBounds(100, 400, 100, 40);

        cmdCancel.setText("Cancel");
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });
        add(cmdCancel);
        cmdCancel.setBounds(340, 400, 80, 40);

        cmdReset.setText("Reset");
        cmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetActionPerformed(evt);
            }
        });
        add(cmdReset);
        cmdReset.setBounds(220, 400, 100, 40);

        optAdmin.setForeground(new java.awt.Color(255, 255, 255));
        optAdmin.setText("Admin");
        optAdmin.setOpaque(false);
        add(optAdmin);
        optAdmin.setBounds(430, 90, 100, 30);

        optAudit.setForeground(new java.awt.Color(255, 255, 255));
        optAudit.setText("Audit");
        optAudit.setOpaque(false);
        add(optAudit);
        optAudit.setBounds(220, 310, 87, 23);

        optBooking.setForeground(new java.awt.Color(255, 255, 255));
        optBooking.setText("Summary");
        optBooking.setOpaque(false);
        add(optBooking);
        optBooking.setBounds(220, 250, 110, 23);

        optStatus.setForeground(new java.awt.Color(255, 255, 255));
        optStatus.setText("Status");
        optStatus.setOpaque(false);
        add(optStatus);
        optStatus.setBounds(220, 280, 87, 23);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Retype");
        add(jLabel5);
        jLabel5.setBounds(100, 180, 90, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
        
        if(verified() && updateToDb())
        {   
            parent.updateList();
            parent.toggle();
            clearAll();
        }
        
           
        
    }//GEN-LAST:event_cmdSaveActionPerformed

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        clearAll();
        parent.toggle();
    }//GEN-LAST:event_cmdCancelActionPerformed

    private void cmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetActionPerformed
        clearAll();
    }//GEN-LAST:event_cmdResetActionPerformed

    public void clearAll()
    {
        isEdited=false;
        currentName="";
        txtUserName.setText(currentName);
        txtPassword1.setText(currentName);
        txtPassword2.setText(currentName);
        
        optAdmin.setSelected(false);
        optAudit.setSelected(false);
        optBooking.setSelected(false);
        optStatus.setSelected(false);
        
    }
    public void serviceRequest(String name)
    {
        String query="Select * from staff where sname='" + name + "'";
        currentName=name;
        isEdited=true;
        
        db.openConnection();
        
        try
        {
            ResultSet rs= db.read(query);
            rs.next();
            String priv=rs.getString("priv");
            
            txtUserName.setText( rs.getString("sname") );
            txtPassword1.setText( rs.getString("pass"));
            txtPassword2.setText( rs.getString("pass"));
            
            optAdmin.setSelected(rs.getBoolean("type"));
            
            if(priv.charAt(0)=='1')
                optBooking.setSelected(true);
            if(priv.charAt(1)=='1')
                optStatus.setSelected(true);
            if(priv.charAt(2)=='1')
                optAudit.setSelected(true);
            
        }
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null, e.getMessage(),"Oops",JOptionPane.ERROR_MESSAGE);
        }
        
        
        db.closeConnection();
        
        
    }
    
    private boolean verified()
    {
        
        String problems="";
        
        if(txtUserName.getText().length() < 6 )
        {
            problems="Name Should be greater than 6 characters\n";
        }
        else if(txtUserName.getText().length() < 6 ||  txtUserName.getText().length() > 30)
        {
            problems="Name Should Be Between 6 and 30 characters Long. \n";
        }
        else if(txtPassword1.getText().length() < 6 ||  txtPassword1.getText().length() > 30)
        {
            problems="Password Should Be Between 6 and 30 characters Long. \n";
        }
        else if(!txtPassword1.getText().contentEquals(txtPassword2.getText()))
        {
            problems="Passwords Donot Match. \n";
        }
        
        
        if(problems.length()!=0)
        {
            JOptionPane.showMessageDialog(null, problems);
            return false;
        }
        
        return true;
        
    }
    
    boolean updateToDb()
    {
        //Code to create strings for admin and priviledges
        String pass;
        String x1;
        String x2;
        String x3;
        
        pass="0";
        x1="0";
        x2="0";
        x3="0";

        
        if(optAdmin.isSelected())
        {
            pass="1";
        }
        
        if(optBooking.isSelected())
        {
            x1="1";
        }
        if(optStatus.isSelected())
        {
            x2="1";
        }
        if(optAudit.isSelected())
        {
            x3="1";
        }

        String x= x1+x2+x3;
        
        /*-----------END OF ALTERATION-------------------*/
        
        
        try
        {
            
            
            if(isEdited)
                UserType.updateUser(txtUserName.getText(), txtPassword1.getText(), pass, x,currentName);
            else
                UserType.addUser(txtUserName.getText(), txtPassword1.getText(), pass, x);
            
            
            
            
            
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Oops",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        
        
        return true;
            
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdReset;
    private javax.swing.JButton cmdSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JCheckBox optAdmin;
    private javax.swing.JCheckBox optAudit;
    private javax.swing.JCheckBox optBooking;
    private javax.swing.JCheckBox optStatus;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
