/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package db;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author osman
 */
public class FrmAddItem extends javax.swing.JPanel {

    /**
     * Creates new form FrmAddItem
     */
    FrmItem parent;
    boolean isEdited=false;
    DatabaseType db= new DatabaseType();
    String currentItem="";
    
    public FrmAddItem(FrmItem p) {
        initComponents();
        parent=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdSave = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();
        cmdReset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtCount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(13, 71, 93));
        setLayout(null);

        cmdSave.setText("Save");
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });
        add(cmdSave);
        cmdSave.setBounds(100, 320, 80, 40);

        cmdCancel.setText("Cancel");
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });
        add(cmdCancel);
        cmdCancel.setBounds(340, 320, 80, 40);

        cmdReset.setText("Reset");
        cmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetActionPerformed(evt);
            }
        });
        add(cmdReset);
        cmdReset.setBounds(220, 320, 80, 40);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CountVal");
        add(jLabel2);
        jLabel2.setBounds(100, 250, 90, 30);

        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });
        add(txtItemName);
        txtItemName.setBounds(220, 90, 200, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        add(jLabel3);
        jLabel3.setBounds(100, 90, 90, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price");
        add(jLabel4);
        jLabel4.setBounds(100, 170, 90, 30);

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        add(txtPrice);
        txtPrice.setBounds(220, 170, 200, 30);

        txtCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountActionPerformed(evt);
            }
        });
        add(txtCount);
        txtCount.setBounds(220, 250, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Item Info");
        add(jLabel6);
        jLabel6.setBounds(190, 10, 160, 50);
    }// </editor-fold>//GEN-END:initComponents

    
    public void serviceRequest(String name)
    {
        String query="Select * from clothes where name='" + name + "'";
        
        currentItem=name;
        isEdited=true;
        
        
        db.openConnection();
        
        try
        {
            ResultSet rs= db.read(query);
            rs.next();
            
            txtItemName.setText(rs.getString("name"));
            txtPrice.setText(rs.getString("price"));
            txtCount.setText(rs.getString("countVal"));
            
            
        }
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(null, e.getMessage(),"Oops",JOptionPane.ERROR_MESSAGE);
        }
        
        db.closeConnection();
       
    }
    
    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountActionPerformed

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
        if(verified() && updateToDb())
        {   
            parent.updateList();
            parent.toggle();
            clearAll();
        }
    }//GEN-LAST:event_cmdSaveActionPerformed

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        clearAll();
        parent.toggle();
    }//GEN-LAST:event_cmdCancelActionPerformed

    private void cmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetActionPerformed
        clearAll();
    }//GEN-LAST:event_cmdResetActionPerformed

    public void clearAll()
    {
        isEdited=false;
        currentItem="";
        txtPrice.setText(currentItem);
        txtCount.setText(currentItem);
        txtItemName.setText(currentItem);
    }
    private boolean verified()
    {
        
        String problems="";
        int myVal;
        
        if(txtItemName.getText().length()==0 ||  txtItemName.getText().length()> 30)
        {
            problems="Item Name Should be between 1 to 30 characters";
        }
       
       try
                {
                 myVal=   Integer.parseInt(txtPrice.getText());
                 if(myVal<=0 || txtPrice.getText().length()==0) throw new Exception("Problem");
                }
       catch(Exception e)
                {
                        problems="Invalid Price given";
                }
       
       
       try
                {
                 myVal=   Integer.parseInt(txtCount.getText());
                 if(myVal<=0 || txtCount.getText().length()==0) throw new Exception("Problem");
                 
                }
       catch(Exception e)
                {
                        problems="Invalid Count Value given";
                }
       
       
        
        if(problems.length()!=0)
        {
            JOptionPane.showMessageDialog(null, problems);
            return false;
        }
        
        return true;
        
    }
    
    boolean updateToDb()
    {
        
        try
        {
            if(isEdited)
            {
                ItemType.updateItem(txtItemName.getText(), txtPrice.getText(), txtCount.getText(),currentItem);
            }
            else
            {
                 ItemType.addItem(txtItemName.getText(), txtPrice.getText(), txtCount.getText());
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Oops",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
            
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdReset;
    private javax.swing.JButton cmdSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCount;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
