/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package db;

/**
 *
 * @author osman
 */
public class FrmUser extends javax.swing.JPanel {

    /**
     * Creates new form FrmUser
     */
    FrmViewUser view=new FrmViewUser(this);
    FrmAddUser add= new FrmAddUser(this);
    
    public FrmUser() {
        initComponents();
        myPanel.add(view);
        myPanel.add(add);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdView = new javax.swing.JButton();
        cmdAdd = new javax.swing.JButton();
        myPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(13, 71, 93));
        setLayout(null);

        cmdView.setText("View");
        cmdView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdViewActionPerformed(evt);
            }
        });
        add(cmdView);
        cmdView.setBounds(130, 140, 80, 60);

        cmdAdd.setText("Add");
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });
        add(cmdAdd);
        cmdAdd.setBounds(130, 260, 80, 60);

        myPanel.setBackground(new java.awt.Color(13, 71, 93));
        myPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(myPanel);
        myPanel.setLayout(myPanelLayout);
        myPanelLayout.setHorizontalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        myPanelLayout.setVerticalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        add(myPanel);
        myPanel.setBounds(340, 10, 640, 490);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdViewActionPerformed
        add.setVisible(false);
        view.setVisible(true);
        view.setBounds(2,2,590,440);
    }//GEN-LAST:event_cmdViewActionPerformed

    private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
        view.setVisible(false);
        add.setVisible(true);
        add.setBounds(2,2,590,440);
    }//GEN-LAST:event_cmdAddActionPerformed

    
    public void toggle()
    {
        view.setVisible(!view.isVisible());
        add.setVisible(!add.isVisible());
        
        if(add.isVisible())
            add.setBounds(2,2,590,440);
        else
            view.setBounds(2,2,590,440);
        
    }
    
    public void updateList()
    {
        view.refresh();
    }
    
    public void provide(String t)
    {
        add.serviceRequest(t);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdView;
    private javax.swing.JPanel myPanel;
    // End of variables declaration//GEN-END:variables
}
