/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package db;

/**
 *
 * @author osman
 */
public class FrmUtilities extends javax.swing.JPanel {

    /**
     * Creates new form FrmItem
     */
    
    
    FrmRatesChange rates= new FrmRatesChange(this);
    
    public FrmUtilities() {
        initComponents();
        myPanel.add(rates);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();
        cmdPrice = new javax.swing.JButton();

        setBackground(new java.awt.Color(13, 71, 93));
        setLayout(null);

        myPanel.setBackground(new java.awt.Color(13, 71, 93));
        myPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(myPanel);
        myPanel.setLayout(myPanelLayout);
        myPanelLayout.setHorizontalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        myPanelLayout.setVerticalGroup(
            myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        add(myPanel);
        myPanel.setBounds(340, 10, 640, 490);

        cmdPrice.setText("Price Change");
        cmdPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPriceActionPerformed(evt);
            }
        });
        add(cmdPrice);
        cmdPrice.setBounds(90, 210, 120, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPriceActionPerformed
        rates.setVisible(true);
        rates.setBounds(10,2,710,500);  
    }//GEN-LAST:event_cmdPriceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdPrice;
    private javax.swing.JPanel myPanel;
    // End of variables declaration//GEN-END:variables
}
